language: java
jdk:
  - oraclejdk8

install:
  - wget http://mirror.metrocast.net/apache/zookeeper/zookeeper-3.4.13/zookeeper-3.4.13.tar.gz
  - tar -xzvf zookeeper-3.4.11.tar.gz
  - pushd zookeeper-3.4.11 && cp conf/zoo_sample.cfg conf/zoo.cfg && bin/zkServer.sh start